site_name: DL Translate
repo_url: https://github.com/xhlulu/dl-translate
nav:
  - index.md
  - references.md
  - contributing.md
  - available_languages.md
theme: material
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
